# <center>UAS (Pagi) : Data Warehouse dan Data Mining</center>

- NIM : 2018230186
- Nama : Ari Purnomo Aji

---

# <u>Soal :</u>
## <font color=red>Berikut Program membangun model regresi (prediksi pembayaran premi asuransi), koreksi dan lengkapi jika ada yang perlu diperbaiki, simpan hasil/model-nya dan gunakan untuk membangun aplikasi web  dengan framework Flask ke server heroku !</font>

---

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### Loading Dataset

In [8]:
df = pd.read_csv('insurance1.csv')
df.head()

age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [10]:
df.describe()

age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [11]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

### Data Preparation - Mengubah data categorical ke numeric

In [13]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
df[['sex','smoker','region']]=oe.fit_transform(df[['sex','smoker','region']])
df[['sex','smoker']]=oe.fit_transform(df[['sex','smoker']])

In [14]:
df[['sex','smoker','region']]=df[['sex','smoker','region']].astype(int)
df[['sex','smoker']]=df[['sex','smoker']].astype(int)

In [15]:
df.head()

age  sex   bmi  children  smoker  region  expenses
0   19    0  27.9         0       1       3  16884.92
1   18    1  33.8         1       0       2   1725.55
2   28    1  33.0         3       0       2   4449.46
3   33    1  22.7         0       0       1  21984.47
4   32    1  28.9         0       0       1   3866.86

In [16]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'expenses'], dtype='object')

### Memisah Feature dan Label

In [19]:
target=df['children']
features=df.drop(columns=['children'])

In [20]:
#Standardization
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
features=sc.fit_transform(features)

In [21]:
pd.DataFrame(features[:5])

0         1         2         3         4         5
0 -1.438764 -1.010519 -0.453646  1.970587  1.343905  0.298583
1 -1.509965  0.989591  0.514186 -0.507463  0.438495 -0.953689
2 -0.797954  0.989591  0.382954 -0.507463  0.438495 -0.728675
3 -0.441948  0.989591 -1.306650 -0.507463 -0.466915  0.719843
4 -0.513149  0.989591 -0.289606 -0.507463 -0.466915 -0.776802

### Membangun Model

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [23]:
x_train,x_test,y_train,y_test=train_test_split(features,target,shuffle=True,train_size=0.8,random_state=1)

In [24]:
len(x_train)

1070

In [25]:
len(x_test)

268

In [26]:
model_uas=LinearRegression()
model_uas.fit(x_train,y_train)

LinearRegression()

### Evaluasi

In [27]:
from sklearn.metrics import r2_score,mean_squared_error
pred=model_uas.predict(x_test)
print('r2 score :',r2_score(y_test,pred))
print('MSE :',mean_squared_error(y_test,pred))

r2 score : 0.014024890952027858
MSE : 1.4078396818391454


In [28]:
print(pred[:5])
print(y_test[:5])

[1.02483227 1.13002587 1.11322997 1.05021467 1.18758147]
559     0
1087    0
1020    0
460     3
802     1
Name: children, dtype: int64


In [29]:
x_test.shape

(268, 6)

In [30]:
type(x_test)

numpy.ndarray

In [31]:
x_test[0,:]

array([-1.43876426,  0.98959079,  0.79305243, -0.5074631 , -0.46691549,
       -0.96022526])

### Menyimpan Model untuk Deployment

Install pickle jika belum ada

  !pip install pickle-mixin

In [2]:
import pickle

pickle.dump(model_uas,open('model_uas.pkl','wb'))

NameError: name 'model_uas' is not defined

Cek file model_uas.pkl, dan gunakan sebagai model saat membangun aplikasi web berbasis Flask

---
### Clue 
Untuk membangun model ini ke aplikasi web Flask server heroku :
- Model terdiri dari 5 atribut input dan 1 output : 

  INPUT :
  - 'age', umur
  - 'sex',  jenis kelamin
  - 'bmi',  berat
  - 'children',  jumlah anak
  - 'smoker',  perokok atau tidak
  
  OUTPUT
  - charges, besar iuran asuransi per bulan
  

In [33]:
#Contoh penggunaan 
age=27
sex=1
bmi=30
children=5
smoker=0
X=np.array([age,sex, bmi, children, smoker])
X=X.reshape(1,-1)
X

array([[27,  1, 30,  5,  0]])

In [34]:
X.shape

(1, 5)

In [1]:
charger_pred=model_uas.predict(X)

NameError: name 'model_uas' is not defined

In [36]:
print("Prediksi Pembayaran premi : ",charger_pred)

NameError: name 'charger_pred' is not defined